services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/website
      - ../logs:/app/logs
    container_name: bookie_app
    depends_on:
      - db
    environment:
      - FLASK_DEBUG=1
      - DATABASE_URL=${DATABASE_URL}
    command: sh -c "python -m flask db upgrade && python -m flask db upgrade && gunicorn -w 4 -b 0.0.0.0:8000 main:app"
  db:
    image: pgvector/pgvector:pg16
    container_name: bookie_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookie
    ports:
      - "5432:5432"
    volumes:
      - bookie_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
volumes:
  bookie_data:
