ALTER USER postgres WITH ENCRYPTED PASSWORD '****';
CREATE USER {user} WITH ENCRYPTED PASSWORD '****';
GRANT ALL PRIVILEGES ON DATABASE bookie TO {user};
GRANT ALL PRIVILEGES ON SCHEMA public TO {user};
CREATE EXTENSION IF NOT EXISTS vector;