"""Centroids

Revision ID: 04bc78a4a4ad
Revises: 5f9c9a662a5f
Create Date: 2025-03-06 19:02:20.271225

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = '04bc78a4a4ad'
down_revision = '5f9c9a662a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('centroid1', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
        batch_op.add_column(sa.Column('centroid2', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
        batch_op.add_column(sa.Column('centroid3', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
        batch_op.add_column(sa.Column('centroid4', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('centroid4')
        batch_op.drop_column('centroid3')
        batch_op.drop_column('centroid2')
        batch_op.drop_column('centroid1')

    # ### end Alembic commands ###
