"""Initial migration

Revision ID: 772274daca5c
Revises: 
Create Date: 2025-03-05 19:48:00.984542

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = '772274daca5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goodreads_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('isbn', sa.String(length=150), nullable=True),
    sa.Column('author', sa.String(length=150), nullable=True),
    sa.Column('num_pages', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=10000), nullable=True),
    sa.Column('cover_image_uri', sa.String(length=150), nullable=True),
    sa.Column('series_length', sa.Integer(), nullable=True),
    sa.Column('year_first_published', sa.Integer(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('tags', sa.String(length=250), nullable=True),
    sa.Column('rating_distribution', sa.String(length=300), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picked_books', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    op.drop_table('session')
    op.drop_table('book')
    # ### end Alembic commands ###
