"""empty message

Revision ID: be3eb9032ed7
Revises: 04bc78a4a4ad
Create Date: 2025-03-09 18:30:25.981398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3eb9032ed7'
down_revision = '04bc78a4a4ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_books',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'book_id')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('picked_books')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picked_books', sa.VARCHAR(), autoincrement=False, nullable=True))

    op.drop_table('session_books')
    # ### end Alembic commands ###
